# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 999999
after_success:
 - julia -e 'import Pkg; cd(Pkg.dir("NumberTheoreticTransforms")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder());)'
