name = "NumberTheoreticTransforms"
uuid = "8497c1d1-af72-4391-8d22-bdd566511a1c"
authors = ["Jakub Wronowski <jakubwro@users.noreply.github.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
