language: julia
julia:
    - 1.0
    - 1.3
    - nightly
notifications:
  email: false
git:
  depth: 3
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=doc/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=doc/ doc/make.jl
      after_success: skip